import type { AuditLog, Bank, Branch, Complaint, Currency, Order, PlatformUser } from "./domain";

export const banks: Bank[] = [
  {
    id: "bank-sparda",
    name: "Sparda Bank Pilot",
    legalName: "Sparda Bank Pilot eG",
    contractStatus: "pilot_ready",
    globalLimitEur: 50000,
  },
  {
    id: "bank-test",
    name: "Kontrollbank Sandbox",
    legalName: "Kontrollbank Sandbox AG",
    contractStatus: "draft",
    globalLimitEur: 10000,
  },
];

export const branches: Branch[] = [
  {
    id: "branch-ffm",
    bankId: "bank-sparda",
    name: "Frankfurt Mitte",
    branchNumber: "FFM-001",
    city: "Frankfurt am Main",
    orderLimitEur: 15000,
  },
  {
    id: "branch-wi",
    bankId: "bank-sparda",
    name: "Wiesbaden Service",
    branchNumber: "WI-002",
    city: "Wiesbaden",
    orderLimitEur: 12000,
  },
  {
    id: "branch-test",
    bankId: "bank-test",
    name: "Sandbox Filiale",
    branchNumber: "TST-001",
    city: "Mainz",
    orderLimitEur: 5000,
  },
];

export const users: PlatformUser[] = [
  {
    id: "user-bank-admin",
    name: "Anna Bankadmin",
    email: "admin@sparda-pilot.example",
    role: "bank_admin",
    bankId: "bank-sparda",
  },
  {
    id: "user-bank",
    name: "Nina Bank",
    email: "bank.user@sparda-pilot.example",
    role: "bank_user",
    bankId: "bank-sparda",
    branchId: "branch-ffm",
  },
  {
    id: "user-approver",
    name: "Mara Freigabe",
    email: "freigabe@sparda-pilot.example",
    role: "bank_approver",
    bankId: "bank-sparda",
  },
  {
    id: "user-ops",
    name: "CashEx Ops",
    email: "ops@cashex.example",
    role: "cashex_ops",
  },
  {
    id: "user-compliance",
    name: "CashEx Compliance",
    email: "compliance@cashex.example",
    role: "cashex_compliance",
  },
  {
    id: "user-management",
    name: "CashEx Management",
    email: "management@cashex.example",
    role: "cashex_management",
  },
  {
    id: "user-revision",
    name: "Revision",
    email: "revision@cashex.example",
    role: "revision",
  },
];

export const currencies: Currency[] = [
  { code: "USD", name: "US-Dollar", active: true },
  { code: "GBP", name: "Britisches Pfund", active: true },
  { code: "CHF", name: "Schweizer Franken", active: true },
  { code: "CAD", name: "Kanadischer Dollar", active: true },
  { code: "AUD", name: "Australischer Dollar", active: true },
  { code: "JPY", name: "Japanischer Yen", active: true },
  { code: "TRY", name: "Tuerkische Lira", active: true },
  { code: "AED", name: "VAE-Dirham", active: true },
];

export const initialOrders: Order[] = [
  {
    id: "order-1000-usd",
    reference: "CX-2026-0001",
    bankId: "bank-sparda",
    branchId: "branch-ffm",
    createdByUserId: "user-bank",
    status: "submitted",
    currencyCode: "USD",
    foreignAmount: 1000,
    eurAmount: 930,
    fxRate: 0.93,
    marginPercent: 2.2,
    handlingFeeEur: 12,
    shippingFeeEur: 18,
    requestedDeliveryDate: "2026-06-08",
    deliveryOption: "standard",
    customerReferenceBank: "SP-FM-REISE-8841",
    shipmentStatus: "not_started",
    complianceFlag: false,
    createdAt: "2026-06-01T10:00:00.000Z",
    updatedAt: "2026-06-01T10:00:00.000Z",
  },
  {
    id: "order-5000-gbp",
    reference: "CX-2026-0002",
    bankId: "bank-sparda",
    branchId: "branch-wi",
    createdByUserId: "user-bank",
    status: "bank_approval_required",
    currencyCode: "GBP",
    foreignAmount: 5000,
    eurAmount: 5900,
    fxRate: 1.18,
    marginPercent: 2.6,
    handlingFeeEur: 25,
    shippingFeeEur: 22,
    requestedDeliveryDate: "2026-06-10",
    deliveryOption: "express",
    customerReferenceBank: "SP-WI-FIRMEN-1190",
    shipmentStatus: "not_started",
    complianceFlag: false,
    createdAt: "2026-06-01T11:30:00.000Z",
    updatedAt: "2026-06-01T11:30:00.000Z",
  },
  {
    id: "order-test-bank",
    reference: "CX-2026-9001",
    bankId: "bank-test",
    branchId: "branch-test",
    createdByUserId: "user-bank",
    status: "submitted",
    currencyCode: "CHF",
    foreignAmount: 800,
    eurAmount: 840,
    fxRate: 1.05,
    marginPercent: 2,
    handlingFeeEur: 10,
    shippingFeeEur: 18,
    requestedDeliveryDate: "2026-06-12",
    deliveryOption: "standard",
    customerReferenceBank: "HIDDEN-FOR-SPARDA",
    shipmentStatus: "not_started",
    complianceFlag: false,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z",
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "audit-seed-1",
    actorUserId: "user-bank",
    actorRole: "bank_user",
    bankId: "bank-sparda",
    orderId: "order-1000-usd",
    action: "order.submitted",
    entityType: "order",
    entityId: "order-1000-usd",
    comment: "Pilotauftrag 1.000 USD eingereicht.",
    createdAt: "2026-06-01T10:00:01.000Z",
  },
  {
    id: "audit-seed-2",
    actorUserId: "user-bank",
    actorRole: "bank_user",
    bankId: "bank-sparda",
    orderId: "order-5000-gbp",
    action: "order.submitted",
    entityType: "order",
    entityId: "order-5000-gbp",
    comment: "Auftrag oberhalb Filiallimit markiert.",
    createdAt: "2026-06-01T11:30:01.000Z",
  },
];

export const initialComplaints: Complaint[] = [];
